name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ------------------------------------------------
  # 🧹 Pre-commit Hooks (linting, formatting, static checks)
  # ------------------------------------------------
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # ✅ Cache dependencies
      - name: Cache UV
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('backend/uv.lock') }}

      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('frontend/bun.lockb') }}

      - name: Install backend dependencies
        working-directory: ./backend
        run: uv sync --all-extras --dev

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: bun install

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  # ------------------------------------------------
  # 🧪 Backend Tests
  # ------------------------------------------------
  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    needs: pre-commit

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v5

      - name: Restore UV cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('backend/uv.lock') }}

      - name: Install dependencies
        working-directory: ./backend
        run: uv sync --all-extras --dev

      - name: Run backend tests with coverage
        working-directory: ./backend
        run: |
          uv run coverage run -m pytest
          uv run coverage xml -o coverage.xml

      # - name: Upload coverage to Codecov (optional)
      #   if: success()
      #   uses: codecov/codecov-action@v5
      #   with:
      #     files: ./backend/coverage.xml
      #     flags: backend

  # ------------------------------------------------
  # 💻 Frontend Tests
  # ------------------------------------------------
  test-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: pre-commit

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Restore Bun cache
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('frontend/bun.lockb') }}

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: bun install

      - name: Run frontend tests
        working-directory: ./frontend
        run: bun run test:coverage

      - name: Build frontend
        working-directory: ./frontend
        run: bun run build