name: Format and Lint

on:
  push:

jobs:
  backend-checks:
    name: Backend (Format, Lint)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/ruff-action@v3

  frontend-checks:
    name: Frontend (Format, Lint)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check formatting with biome
        run: bun run biome format ./src

      - name: Lint with biome
        run: bun run biome lint ./src

      - name: Type check
        run: bun run typecheck

